Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
KerasH5: KERAS_3layer_weights.h5
KerasJson: KERAS_3layer.json
OutputDir: my-hls-test
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: 1ebCABAA
Version: 1.0.0
