// Generated by CIRCT firtool-1.54.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ProcessingElement(	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
  input         clock,	// <stdin>:17:11, :57:11, :97:11, :137:11, :177:11, :217:11, :257:11, :297:11, :337:11, :377:11, :417:11, :457:11, :497:11, :537:11, :577:11, :617:11
                reset,	// <stdin>:18:11, :58:11, :98:11, :138:11, :178:11, :218:11, :258:11, :298:11, :338:11, :378:11, :418:11, :458:11, :498:11, :538:11, :578:11, :618:11
  input  [15:0] io_aIn,	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
                io_bIn,	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
  output [15:0] io_aOut,	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
                io_bOut,	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
                io_cOut	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
);

  reg [15:0] aReg;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
  reg [15:0] bReg;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:21:21
  reg [31:0] cReg;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:22:21
  always @(posedge clock) begin	// <stdin>:17:11, :57:11, :97:11, :137:11, :177:11, :217:11, :257:11, :297:11, :337:11, :377:11, :417:11, :457:11, :497:11, :537:11, :577:11, :617:11
    if (reset) begin	// <stdin>:17:11, :57:11, :97:11, :137:11, :177:11, :217:11, :257:11, :297:11, :337:11, :377:11, :417:11, :457:11, :497:11, :537:11, :577:11, :617:11
      aReg <= 16'h0;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
      bReg <= 16'h0;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21, :21:21
      cReg <= 32'h0;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:22:21
    end
    else begin	// <stdin>:17:11, :57:11, :97:11, :137:11, :177:11, :217:11, :257:11, :297:11, :337:11, :377:11, :417:11, :457:11, :497:11, :537:11, :577:11, :617:11
      aReg <= io_aIn;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
      bReg <= io_bIn;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:21:21
      cReg <= {16'h0, io_aIn} * {16'h0, io_bIn} + cReg;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21, :22:21, :26:{18,27}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
      `FIRRTL_BEFORE_INITIAL	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
      automatic logic [31:0] _RANDOM[0:1];	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
        `INIT_RANDOM_PROLOG_	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
        end	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
        aReg = _RANDOM[1'h0][15:0];	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
        bReg = _RANDOM[1'h0][31:16];	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21, :21:21
        cReg = _RANDOM[1'h1];	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:22:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
      `FIRRTL_AFTER_INITIAL	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_aOut = aReg;	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
  assign io_bOut = bReg;	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:21:21
  assign io_cOut = cReg[15:0];	// <stdin>:16:3, :56:3, :96:3, :136:3, :176:3, :216:3, :256:3, :296:3, :336:3, :376:3, :416:3, :456:3, :496:3, :536:3, :576:3, :616:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:22:21, :35:11
endmodule

module SystolicArray(	// <stdin>:643:3
  input         clock,	// <stdin>:644:11
                reset,	// <stdin>:645:11
  input  [15:0] io_a_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_a_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_a_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_a_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_b_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_b_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_b_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_b_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
  input  [3:0]  io_fixedPoint,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
  output [15:0] io_c_0_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_0_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_0_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_0_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_1_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_1_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_1_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_1_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_2_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_2_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_2_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_2_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_3_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_3_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_3_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
                io_c_3_3	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
);

  wire [15:0] _ProcessingElement_14_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_13_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_12_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_11_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_10_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_10_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_9_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_9_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_8_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_8_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_7_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_6_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_6_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_5_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_5_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_4_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_4_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_3_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_2_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_2_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_1_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_1_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [15:0] _ProcessingElement_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  ProcessingElement ProcessingElement (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (io_a_0),
    .io_bIn  (io_b_0),
    .io_aOut (_ProcessingElement_io_aOut),
    .io_bOut (_ProcessingElement_io_bOut),
    .io_cOut (io_c_0_0)
  );
  ProcessingElement ProcessingElement_1 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (io_a_1),
    .io_bIn  (_ProcessingElement_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_1_io_aOut),
    .io_bOut (_ProcessingElement_1_io_bOut),
    .io_cOut (io_c_0_1)
  );
  ProcessingElement ProcessingElement_2 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (io_a_2),
    .io_bIn  (_ProcessingElement_1_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_2_io_aOut),
    .io_bOut (_ProcessingElement_2_io_bOut),
    .io_cOut (io_c_0_2)
  );
  ProcessingElement ProcessingElement_3 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (io_a_3),
    .io_bIn  (_ProcessingElement_2_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_3_io_aOut),
    .io_bOut (/* unused */),
    .io_cOut (io_c_0_3)
  );
  ProcessingElement ProcessingElement_4 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (io_b_1),
    .io_aOut (_ProcessingElement_4_io_aOut),
    .io_bOut (_ProcessingElement_4_io_bOut),
    .io_cOut (io_c_1_0)
  );
  ProcessingElement ProcessingElement_5 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_1_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_4_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_5_io_aOut),
    .io_bOut (_ProcessingElement_5_io_bOut),
    .io_cOut (io_c_1_1)
  );
  ProcessingElement ProcessingElement_6 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_2_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_5_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_6_io_aOut),
    .io_bOut (_ProcessingElement_6_io_bOut),
    .io_cOut (io_c_1_2)
  );
  ProcessingElement ProcessingElement_7 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_3_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_6_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_7_io_aOut),
    .io_bOut (/* unused */),
    .io_cOut (io_c_1_3)
  );
  ProcessingElement ProcessingElement_8 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_4_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (io_b_2),
    .io_aOut (_ProcessingElement_8_io_aOut),
    .io_bOut (_ProcessingElement_8_io_bOut),
    .io_cOut (io_c_2_0)
  );
  ProcessingElement ProcessingElement_9 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_5_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_8_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_9_io_aOut),
    .io_bOut (_ProcessingElement_9_io_bOut),
    .io_cOut (io_c_2_1)
  );
  ProcessingElement ProcessingElement_10 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_6_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_9_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_10_io_aOut),
    .io_bOut (_ProcessingElement_10_io_bOut),
    .io_cOut (io_c_2_2)
  );
  ProcessingElement ProcessingElement_11 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_7_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_10_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_11_io_aOut),
    .io_bOut (/* unused */),
    .io_cOut (io_c_2_3)
  );
  ProcessingElement ProcessingElement_12 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_8_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (io_b_3),
    .io_aOut (/* unused */),
    .io_bOut (_ProcessingElement_12_io_bOut),
    .io_cOut (io_c_3_0)
  );
  ProcessingElement ProcessingElement_13 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_9_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_12_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (/* unused */),
    .io_bOut (_ProcessingElement_13_io_bOut),
    .io_cOut (io_c_3_1)
  );
  ProcessingElement ProcessingElement_14 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_10_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_13_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (/* unused */),
    .io_bOut (_ProcessingElement_14_io_bOut),
    .io_cOut (io_c_3_2)
  );
  ProcessingElement ProcessingElement_15 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_11_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_14_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (/* unused */),
    .io_bOut (/* unused */),
    .io_cOut (io_c_3_3)
  );
endmodule

