// Generated by CIRCT firtool-1.54.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ProcessingElement(	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
  input        clock,	// <stdin>:17:11, :56:11, :95:11, :134:11, :173:11, :212:11, :251:11, :290:11, :329:11, :368:11, :407:11, :446:11, :485:11, :524:11, :563:11, :602:11
               reset,	// <stdin>:18:11, :57:11, :96:11, :135:11, :174:11, :213:11, :252:11, :291:11, :330:11, :369:11, :408:11, :447:11, :486:11, :525:11, :564:11, :603:11
  input  [7:0] io_aIn,	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
               io_bIn,	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
  output [7:0] io_aOut,	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
               io_bOut,	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
               io_cOut	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:8:14
);

  reg [7:0]  aReg;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
  reg [7:0]  bReg;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:21:21
  reg [15:0] cReg;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:22:21
  always @(posedge clock) begin	// <stdin>:17:11, :56:11, :95:11, :134:11, :173:11, :212:11, :251:11, :290:11, :329:11, :368:11, :407:11, :446:11, :485:11, :524:11, :563:11, :602:11
    if (reset) begin	// <stdin>:17:11, :56:11, :95:11, :134:11, :173:11, :212:11, :251:11, :290:11, :329:11, :368:11, :407:11, :446:11, :485:11, :524:11, :563:11, :602:11
      aReg <= 8'h0;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
      bReg <= 8'h0;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21, :21:21
      cReg <= 16'h0;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:22:21
    end
    else begin	// <stdin>:17:11, :56:11, :95:11, :134:11, :173:11, :212:11, :251:11, :290:11, :329:11, :368:11, :407:11, :446:11, :485:11, :524:11, :563:11, :602:11
      aReg <= io_aIn;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
      bReg <= io_bIn;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:21:21
      cReg <= {8'h0, io_aIn} * {8'h0, io_bIn} + cReg;	// \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21, :22:21, :26:{18,27}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
      `FIRRTL_BEFORE_INITIAL	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
      automatic logic [31:0] _RANDOM[0:0];	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
        `INIT_RANDOM_PROLOG_	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
        aReg = _RANDOM[/*Zero width*/ 1'b0][7:0];	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
        bReg = _RANDOM[/*Zero width*/ 1'b0][15:8];	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21, :21:21
        cReg = _RANDOM[/*Zero width*/ 1'b0][31:16];	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21, :22:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
      `FIRRTL_AFTER_INITIAL	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_aOut = aReg;	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:20:21
  assign io_bOut = bReg;	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:21:21
  assign io_cOut = cReg[7:0];	// <stdin>:16:3, :55:3, :94:3, :133:3, :172:3, :211:3, :250:3, :289:3, :328:3, :367:3, :406:3, :445:3, :484:3, :523:3, :562:3, :601:3, \\src\\main\\scala\\systolic_array\\ProcessingElement.scala:22:21, :36:11
endmodule

module SystolicArray(	// <stdin>:627:3
  input        clock,	// <stdin>:628:11
               reset,	// <stdin>:629:11
  input  [7:0] io_a_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_a_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_a_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_a_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_b_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_b_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_b_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_b_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
  input  [2:0] io_fixedPoint,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
  output [7:0] io_c_0_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_0_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_0_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_0_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_1_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_1_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_1_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_1_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_2_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_2_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_2_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_2_3,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_3_0,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_3_1,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_3_2,	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
               io_c_3_3	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:7:14
);

  wire [7:0] _ProcessingElement_14_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_13_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_12_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_11_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_10_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_10_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_9_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_9_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_8_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_8_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_7_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_6_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_6_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_5_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_5_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_4_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_4_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_3_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_2_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_2_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_1_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_1_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_io_aOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  wire [7:0] _ProcessingElement_io_bOut;	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
  ProcessingElement ProcessingElement (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (io_a_0),
    .io_bIn  (io_b_0),
    .io_aOut (_ProcessingElement_io_aOut),
    .io_bOut (_ProcessingElement_io_bOut),
    .io_cOut (io_c_0_0)
  );
  ProcessingElement ProcessingElement_1 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (io_a_1),
    .io_bIn  (_ProcessingElement_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_1_io_aOut),
    .io_bOut (_ProcessingElement_1_io_bOut),
    .io_cOut (io_c_0_1)
  );
  ProcessingElement ProcessingElement_2 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (io_a_2),
    .io_bIn  (_ProcessingElement_1_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_2_io_aOut),
    .io_bOut (_ProcessingElement_2_io_bOut),
    .io_cOut (io_c_0_2)
  );
  ProcessingElement ProcessingElement_3 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (io_a_3),
    .io_bIn  (_ProcessingElement_2_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_3_io_aOut),
    .io_bOut (/* unused */),
    .io_cOut (io_c_0_3)
  );
  ProcessingElement ProcessingElement_4 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (io_b_1),
    .io_aOut (_ProcessingElement_4_io_aOut),
    .io_bOut (_ProcessingElement_4_io_bOut),
    .io_cOut (io_c_1_0)
  );
  ProcessingElement ProcessingElement_5 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_1_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_4_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_5_io_aOut),
    .io_bOut (_ProcessingElement_5_io_bOut),
    .io_cOut (io_c_1_1)
  );
  ProcessingElement ProcessingElement_6 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_2_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_5_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_6_io_aOut),
    .io_bOut (_ProcessingElement_6_io_bOut),
    .io_cOut (io_c_1_2)
  );
  ProcessingElement ProcessingElement_7 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_3_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_6_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_7_io_aOut),
    .io_bOut (/* unused */),
    .io_cOut (io_c_1_3)
  );
  ProcessingElement ProcessingElement_8 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_4_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (io_b_2),
    .io_aOut (_ProcessingElement_8_io_aOut),
    .io_bOut (_ProcessingElement_8_io_bOut),
    .io_cOut (io_c_2_0)
  );
  ProcessingElement ProcessingElement_9 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_5_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_8_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_9_io_aOut),
    .io_bOut (_ProcessingElement_9_io_bOut),
    .io_cOut (io_c_2_1)
  );
  ProcessingElement ProcessingElement_10 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_6_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_9_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_10_io_aOut),
    .io_bOut (_ProcessingElement_10_io_bOut),
    .io_cOut (io_c_2_2)
  );
  ProcessingElement ProcessingElement_11 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_7_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_10_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (_ProcessingElement_11_io_aOut),
    .io_bOut (/* unused */),
    .io_cOut (io_c_2_3)
  );
  ProcessingElement ProcessingElement_12 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_8_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (io_b_3),
    .io_aOut (/* unused */),
    .io_bOut (_ProcessingElement_12_io_bOut),
    .io_cOut (io_c_3_0)
  );
  ProcessingElement ProcessingElement_13 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_9_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_12_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (/* unused */),
    .io_bOut (_ProcessingElement_13_io_bOut),
    .io_cOut (io_c_3_1)
  );
  ProcessingElement ProcessingElement_14 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_10_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_13_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (/* unused */),
    .io_bOut (_ProcessingElement_14_io_bOut),
    .io_cOut (io_c_3_2)
  );
  ProcessingElement ProcessingElement_15 (	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .clock   (clock),
    .reset   (reset),
    .io_aIn  (_ProcessingElement_11_io_aOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_bIn  (_ProcessingElement_14_io_bOut),	// \\src\\main\\scala\\systolic_array\\SystolicArray.scala:15:69
    .io_aOut (/* unused */),
    .io_bOut (/* unused */),
    .io_cOut (io_c_3_3)
  );
endmodule

